name = "notifytg"
main = "src/index.js"
compatibility_date = "2023-05-12"
[ vars ]
TOKEN = "5025503931:AAG4xw5sw-yNheLzfHKZY8wBxUf9nP-JL_M"
send_email = [
    {type = "send_email", name = "SEB"},
]
CFURL = "https://tg.hello-daf.workers.dev/"

[[ d1_databases ]]
binding = "DB"
database_name = "emaildb"
database_id = "CFWTGW"
